Add editor config and update additional lint rules
RetroShare/RSNewWebUI pull request #29
Opened 2021-04-05 19:56 UTC by rottencandy

Everyone uses different editors/IDEs which have their own defaults. This creates lots of unimportant changes and inconsistency in commits.

Having default formats specified would make it easier to maintain standard stuff like indentations and quotes and a linter will also catch commonly occurring syntax bugs.

2021-04-05 19:57 UTC, rottencandy commented
@zeners @Kumaravinash9 I've added some editor defaults here, if you like extra options or more settings, we can add them in the config here.

2021-04-06 13:26 UTC, Kumaravinash9 commented
@rottencandy,  It could be much better if we add pipeline testing to check if the coding is formatted or not.

2021-04-06 13:29 UTC, rottencandy commented
> @rottencandy, It could be much better if we add pipeline testing to check if the coding is formatted or not.

@csoler would it be a good idea to add a GitHub action that runs a linter on every PR?

2021-04-06 13:57 UTC, Kumaravinash9 requested changes

2021-04-07 13:45 UTC, Kumaravinash9 commented on webui-src/.prettierrc
> +    "arrowParens": "always",
```javascript
"trailingComma": "es5",
"bracketSpacing": "true",
```

2021-04-07 18:07 UTC, rottencandy commented on webui-src/.eslintrc.json
> +        ],
Updated.

2021-04-09 02:38 UTC, Kumaravinash9 commented
@rottencandy, we should add a .prettierignore file for the directory make-src. So, it will not create conflicts whenever we will run prettier.

2021-04-15 18:22 UTC, rottencandy commented
Merging the PR, we can run `eslint` locally for now.
And editorconfig should handle common syntax & indentation for all supported editors.

2021-04-15 18:22 UTC, merged